# Generated by Django 5.0.6 on 2025-10-27 01:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('length_km', models.FloatField(blank=True, help_text='Circuit length in kilometers', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Circuit',
                'verbose_name_plural': 'Circuits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='3-letter driver code (e.g., VER, HAM)', max_length=3)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2022)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('color_secondary', models.CharField(blank=True, help_text='Secondary hex color', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50, unique=True)),
                ('round_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('event_name', models.CharField(help_text='Official event name', max_length=200)),
                ('event_type', models.CharField(choices=[('race', 'Race Weekend'), ('sprint', 'Sprint Weekend'), ('testing', 'Testing')], default='race', max_length=20)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.circuit')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.season')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['season', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('session_type', models.CharField(choices=[('FP1', 'Free Practice 1'), ('FP2', 'Free Practice 2'), ('FP3', 'Free Practice 3'), ('Q', 'Qualifying'), ('S', 'Sprint'), ('SQ', 'Sprint Qualifying'), ('R', 'Race')], max_length=3)),
                ('session_date', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('data_collected', models.BooleanField(default=False)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.event')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['event', 'session_date'],
            },
        ),
        migrations.CreateModel(
            name='SprintResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grid_position', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0.0)),
                ('laps_completed', models.IntegerField(default=0)),
                ('total_sprint_time', models.DurationField(blank=True, null=True)),
                ('fastest_lap_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(default='Finished', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_results', to='core.team')),
            ],
            options={
                'verbose_name': 'Sprint Result',
                'verbose_name_plural': 'Sprint Results',
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grid_position', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(default=0.0)),
                ('laps_completed', models.IntegerField(default=0)),
                ('total_race_time', models.DurationField(blank=True, null=True)),
                ('fastest_lap_time', models.DurationField(blank=True, null=True)),
                ('fastest_lap_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Finished', max_length=50)),
                ('dnf', models.BooleanField(default=False, help_text='Did Not Finish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='core.team')),
            ],
            options={
                'verbose_name': 'Race Result',
                'verbose_name_plural': 'Race Results',
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('q1_time', models.DurationField(blank=True, null=True)),
                ('q2_time', models.DurationField(blank=True, null=True)),
                ('q3_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_results', to='core.team')),
            ],
            options={
                'verbose_name': 'Qualifying Result',
                'verbose_name_plural': 'Qualifying Results',
                'ordering': ['session', 'position'],
            },
        ),
        migrations.CreateModel(
            name='PitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lap', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pit_stops', to='core.team')),
            ],
            options={
                'verbose_name': 'Pit Stop',
                'verbose_name_plural': 'Pit Stops',
                'ordering': ['session', 'lap'],
            },
        ),
        migrations.CreateModel(
            name='LapTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lap_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('lap_time', models.DurationField()),
                ('sector1_time', models.DurationField(blank=True, null=True)),
                ('sector2_time', models.DurationField(blank=True, null=True)),
                ('sector3_time', models.DurationField(blank=True, null=True)),
                ('is_personal_best', models.BooleanField(default=False)),
                ('is_accurate', models.BooleanField(default=True, help_text='Whether the lap time is accurate')),
                ('compound', models.CharField(blank=True, help_text='Tyre compound used', max_length=20)),
                ('tyre_life', models.IntegerField(blank=True, help_text='Age of tyres in laps', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lap_times', to='core.team')),
            ],
            options={
                'verbose_name': 'Lap Time',
                'verbose_name_plural': 'Lap Times',
                'ordering': ['session', 'lap_number', 'driver'],
            },
        ),
        migrations.CreateModel(
            name='DriverStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.FloatField(default=0.0)),
                ('wins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.driver')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='core.event')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_standings', to='core.team')),
            ],
            options={
                'verbose_name': 'Driver Standing',
                'verbose_name_plural': 'Driver Standings',
                'ordering': ['season', 'event', 'position'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('points', models.FloatField(default=0.0)),
                ('wins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='core.event')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_standings', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='core.team')),
            ],
            options={
                'verbose_name': 'Constructor Standing',
                'verbose_name_plural': 'Constructor Standings',
                'ordering': ['season', 'event', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance along track in meters')),
                ('speed', models.FloatField(help_text='Speed in km/h')),
                ('throttle', models.FloatField(help_text='Throttle percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('brake', models.BooleanField(default=False)),
                ('drs', models.IntegerField(help_text='DRS status')),
                ('gear', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('rpm', models.IntegerField(blank=True, help_text='Engine RPM', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lap_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.laptime')),
            ],
            options={
                'verbose_name': 'Telemetry Data',
                'verbose_name_plural': 'Telemetry Data',
                'ordering': ['lap_time', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='TyreStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stint_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('compound', models.CharField(choices=[('SOFT', 'Soft'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('INTERMEDIATE', 'Intermediate'), ('WET', 'Wet')], max_length=15)),
                ('start_lap', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('end_lap', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stint_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('avg_lap_time', models.DurationField(blank=True, null=True)),
                ('fastest_lap_time', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_strategies', to='core.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_strategies', to='core.session')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_strategies', to='core.team')),
            ],
            options={
                'verbose_name': 'Tyre Strategy',
                'verbose_name_plural': 'Tyre Strategies',
                'ordering': ['session', 'driver', 'stint_number'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('air_temp', models.FloatField(help_text='Air temperature in Celsius')),
                ('track_temp', models.FloatField(help_text='Track temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.FloatField(help_text='Atmospheric pressure in mbar')),
                ('rainfall', models.BooleanField(default=False)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='core.session')),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['session', 'timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['season', 'round_number'], name='core_event_season__e46b76_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='core_event_event_d_ed494e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('season', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['event', 'session_type'], name='core_sessio_event_i_c93474_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_date'], name='core_sessio_session_b5c8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sprintresult',
            index=models.Index(fields=['session', 'position'], name='core_sprint_session_e41bae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sprintresult',
            unique_together={('session', 'driver')},
        ),
        migrations.AddIndex(
            model_name='raceresult',
            index=models.Index(fields=['session', 'position'], name='core_racere_session_31cf04_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='raceresult',
            unique_together={('session', 'driver')},
        ),
        migrations.AddIndex(
            model_name='qualifyingresult',
            index=models.Index(fields=['session', 'position'], name='core_qualif_session_70b26e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualifyingresult',
            unique_together={('session', 'driver')},
        ),
        migrations.AddIndex(
            model_name='pitstop',
            index=models.Index(fields=['session', 'driver'], name='core_pitsto_session_764ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pitstop',
            unique_together={('session', 'driver', 'stop_number')},
        ),
        migrations.AddIndex(
            model_name='laptime',
            index=models.Index(fields=['session', 'driver'], name='core_laptim_session_e2929c_idx'),
        ),
        migrations.AddIndex(
            model_name='laptime',
            index=models.Index(fields=['session', 'lap_number'], name='core_laptim_session_40bbaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laptime',
            unique_together={('session', 'driver', 'lap_number')},
        ),
        migrations.AddIndex(
            model_name='driverstanding',
            index=models.Index(fields=['season', 'event', 'position'], name='core_driver_season__335555_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driverstanding',
            unique_together={('season', 'event', 'driver')},
        ),
        migrations.AddIndex(
            model_name='constructorstanding',
            index=models.Index(fields=['season', 'event', 'position'], name='core_constr_season__5310f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructorstanding',
            unique_together={('season', 'event', 'team')},
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['lap_time', 'distance'], name='core_teleme_lap_tim_7c2e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='tyrestrategy',
            index=models.Index(fields=['session', 'driver'], name='core_tyrest_session_5dcf2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tyrestrategy',
            unique_together={('session', 'driver', 'stint_number')},
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['session', 'timestamp'], name='core_weathe_session_7b67a8_idx'),
        ),
    ]
