# Generated by Django 5.0.6 on 2025-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorstanding',
            name='podiums',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverstanding',
            name='podiums',
            field=models.IntegerField(default=0),
        ),
    ]
