# Generated by Django 5.0.6 on 2025-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constructorstanding_podiums_driverstanding_podiums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitstop',
            name='duration',
            field=models.DurationField(blank=True, help_text='Pit stop duration (can be null if not available)', null=True),
        ),
    ]
