# Generated by Django 5.0.6 on 2025-11-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pitstop_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='canonical_name',
            field=models.CharField(blank=True, help_text="Nome consolidado da equipe para análises históricas. Ex: 'Alpine' para Renault/Alpine F1 Team", max_length=100),
        ),
    ]
