# Generated by Django 5.0.6 on 2025-11-08 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_team_canonical_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
    ]
