# Generated by Django 5.0.6 on 2025-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_season_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('FASTF1', 'FastF1 API'), ('JOLPICA', 'Jolpica/Ergast API'), ('ML', 'Machine Learning'), ('SYSTEM', 'System')], db_index=True, max_length=20)),
                ('task_name', models.CharField(help_text='Nome da tarefa Celery', max_length=200)),
                ('message', models.TextField(help_text='Mensagem de log')),
                ('exception_type', models.CharField(blank=True, help_text='Tipo da exceção (se houver)', max_length=200)),
                ('traceback', models.TextField(blank=True, help_text='Stack trace completo')),
                ('year', models.IntegerField(blank=True, help_text='Ano relacionado', null=True)),
                ('round_number', models.IntegerField(blank=True, help_text='Número da rodada', null=True)),
                ('session_type', models.CharField(blank=True, help_text='Tipo de sessão (R, Q, S, etc.)', max_length=50)),
                ('task_id', models.CharField(blank=True, help_text='ID da tarefa Celery', max_length=255)),
                ('resolved', models.BooleanField(default=False, help_text='Problema resolvido?')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notas sobre a resolução')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data Collection Log',
                'verbose_name_plural': 'Data Collection Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='core_dataco_created_77c5a4_idx'), models.Index(fields=['source', 'level'], name='core_dataco_source_8afb83_idx'), models.Index(fields=['resolved', 'level'], name='core_dataco_resolve_cbc628_idx')],
            },
        ),
    ]
