# Generated by Django 5.0.6 on 2025-11-09 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_data_collection_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Tempo de execução em segundos', null=True)),
                ('total_tables_scanned', models.IntegerField(default=0)),
                ('total_fields_scanned', models.IntegerField(default=0)),
                ('total_empty_fields_found', models.IntegerField(default=0)),
                ('total_suggestions_found', models.IntegerField(default=0)),
                ('audit_results', models.JSONField(default=dict, help_text='Resultados completos da auditoria em formato JSON')),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se a execução falhou')),
            ],
            options={
                'verbose_name': 'Data Audit Report',
                'verbose_name_plural': 'Data Audit Reports',
                'ordering': ['-execution_date'],
                'indexes': [models.Index(fields=['-execution_date'], name='core_dataau_executi_fa6541_idx'), models.Index(fields=['status'], name='core_dataau_status_28fa6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataAuditSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(help_text='ID do registro com campo vazio')),
                ('record_identifier', models.CharField(help_text="Identificador legível do registro (ex: 'Max Verstappen', 'Monaco GP')", max_length=200)),
                ('current_value', models.TextField(blank=True, help_text='Valor atual (geralmente vazio ou NULL)', null=True)),
                ('suggested_value', models.TextField(help_text='Valor sugerido encontrado na web')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confiança da sugestão (0.0 a 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source_name', models.CharField(help_text='Nome da fonte (Wikipedia, Wikidata, etc.)', max_length=100)),
                ('source_url', models.URLField(help_text='URL da fonte da informação')),
                ('source_timestamp', models.DateTimeField(auto_now_add=True, help_text='Quando a informação foi obtida')),
                ('applied', models.BooleanField(default=False, help_text='Sugestão foi aplicada?')),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected', models.BooleanField(default=False, help_text='Sugestão foi rejeitada?')),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.dataauditreport')),
            ],
            options={
                'verbose_name': 'Data Audit Suggestion',
                'verbose_name_plural': 'Data Audit Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report', 'table_name'], name='core_dataau_report__55aba8_idx'), models.Index(fields=['applied', 'rejected'], name='core_dataau_applied_917de3_idx')],
            },
        ),
    ]
