# Generated by Django 5.0.6 on 2025-11-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_data_audit_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(help_text='3-letter driver code (e.g., VER, HAM)', max_length=3, unique=True),
        ),
    ]
