# Generated by Django 5.0.6 on 2025-11-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_unique_driver_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_name',
            field=models.CharField(blank=True, db_index=True, help_text='Nome mais recente da operação (para exibição nos filtros)', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='display_in_filters',
            field=models.BooleanField(db_index=True, default=True, help_text='Se True, mostra nos filtros da UI. False para nomes históricos.'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_engine_variant',
            field=models.BooleanField(default=False, help_text='True se for apenas variação de motor (ex: Cooper-Climax)'),
        ),
        migrations.AddField(
            model_name='team',
            name='operation_line_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID da linha de operação (ex: 1=Ferrari, 2=Mercedes, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='Equipe predecessora na linha de sucessão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='core.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('RENAMED', 'Renomeada'), ('EXTINCT', 'Extinta'), ('MERGED', 'Fundida')], default='ACTIVE', help_text='Status atual da equipe', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='years_active',
            field=models.CharField(blank=True, help_text="Anos em que este nome foi usado (ex: '1997-1999')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['operation_line_id'], name='core_team_operati_b29b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['display_in_filters'], name='core_team_display_34b67b_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['current_name'], name='core_team_current_3166b6_idx'),
        ),
    ]
