# Generated by Django 5.0.6 on 2025-11-17 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_team_current_name_team_display_in_filters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDataCollectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_workers', models.IntegerField(default=10, help_text='Número máximo de workers Celery para coleta histórica (1-50)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('tasks_per_batch', models.IntegerField(default=20, help_text='Número de tarefas executadas em paralelo por lote (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('enabled', models.BooleanField(default=True, help_text='Ativar/desativar coleta automática de dados históricos')),
                ('scan_interval_minutes', models.IntegerField(default=5, help_text='Intervalo de varredura em minutos (1-60)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('start_year', models.IntegerField(default=2024, help_text='Ano inicial para coleta (mais recente para mais antigo)', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)])),
                ('end_year', models.IntegerField(default=1950, help_text='Ano final para coleta (não incluso)', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)])),
                ('collect_races', models.BooleanField(default=True, help_text='Coletar resultados de corridas')),
                ('collect_qualifying', models.BooleanField(default=True, help_text='Coletar resultados de qualificação')),
                ('collect_sprints', models.BooleanField(default=True, help_text='Coletar resultados de sprints')),
                ('collect_standings', models.BooleanField(default=True, help_text='Coletar classificações')),
                ('collect_drivers', models.BooleanField(default=True, help_text='Coletar dados de pilotos')),
                ('collect_teams', models.BooleanField(default=True, help_text='Coletar dados de equipes')),
                ('collect_circuits', models.BooleanField(default=True, help_text='Coletar dados de circuitos')),
                ('use_wikipedia', models.BooleanField(default=True, help_text='Usar Wikipedia como fonte para dados históricos (pré-2018)')),
                ('use_ergast_api', models.BooleanField(default=True, help_text='Usar Ergast API como fonte para dados históricos')),
                ('last_scan_at', models.DateTimeField(blank=True, help_text='Última execução da varredura', null=True)),
                ('last_year_processed', models.IntegerField(blank=True, help_text='Último ano processado com sucesso', null=True)),
                ('total_records_collected', models.IntegerField(default=0, help_text='Total de registros coletados desde o início')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historical Data Collection Config',
                'verbose_name_plural': 'Historical Data Collection Configs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gap_type', models.CharField(choices=[('season', 'Temporada Completa'), ('event', 'Evento/GP'), ('session', 'Sessão'), ('result', 'Resultado'), ('standing', 'Classificação'), ('driver', 'Piloto'), ('team', 'Equipe'), ('circuit', 'Circuito')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('collecting', 'Coletando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], db_index=True, default='pending', max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)])),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(help_text='Descrição do gap identificado')),
                ('priority', models.IntegerField(default=100, help_text='Prioridade de coleta (0-1000, maior = mais prioritário)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historical Data Gap',
                'verbose_name_plural': 'Historical Data Gaps',
                'ordering': ['-priority', '-year', 'round_number'],
                'indexes': [models.Index(fields=['status', '-priority'], name='core_histor_status_233f72_idx'), models.Index(fields=['year', 'round_number'], name='core_histor_year_938050_idx'), models.Index(fields=['-created_at'], name='core_histor_created_5b93ef_idx')],
            },
        ),
    ]
