# Generated by Django 5.0.6 on 2025-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historicaldatacollectionconfig_historicaldatagap'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldatagap',
            name='data_source',
            field=models.CharField(blank=True, help_text='Fonte de dados utilizada (ex: Ergast/Jolpica, Wikipedia, StatsF1, etc)', max_length=50),
        ),
    ]
