# Generated by Django 5.0.6 on 2025-11-19 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_data_source_to_historical_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldatacollectionconfig',
            name='end_year',
            field=models.IntegerField(default=1950, help_text='Ano final para coleta histórica (mais antigo)', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.AlterField(
            model_name='historicaldatacollectionconfig',
            name='start_year',
            field=models.IntegerField(default=2017, help_text='Ano inicial para coleta histórica (mais recente) - máximo 2017 pois FastF1 API cobre 2018+', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.CreateModel(
            name='TeamOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(help_text="Nome da operação (ex: 'Red Bull Racing', 'Mercedes-AMG F1', 'Scuderia Ferrari')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição da linhagem histórica da operação')),
                ('year_founded', models.IntegerField(blank=True, help_text='Ano de fundação da operação original', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('year_ended', models.IntegerField(blank=True, help_text='Ano de encerramento (se aplicável)', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('is_active', models.BooleanField(default=True, help_text='Se a operação está ativa atualmente na F1')),
                ('total_wins', models.IntegerField(default=0, help_text='Total de vitórias de todas as equipes da operação')),
                ('total_podiums', models.IntegerField(default=0, help_text='Total de pódios de todas as equipes da operação')),
                ('total_championships', models.IntegerField(default=0, help_text='Total de campeonatos (pilotos + construtores)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Usuário que criou esta operação', max_length=100)),
                ('primary_team', models.ForeignKey(blank=True, help_text='Equipe principal/atual que representa esta operação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_as_primary', to='core.team')),
                ('teams', models.ManyToManyField(blank=True, help_text='Todas as equipes que fazem parte desta linhagem/operação', related_name='operations', to='core.team')),
            ],
            options={
                'verbose_name': 'Operação de Equipe',
                'verbose_name_plural': 'Operações de Equipes',
                'ordering': ['-is_active', 'operation_name'],
                'indexes': [models.Index(fields=['operation_name'], name='core_teamop_operati_52041c_idx'), models.Index(fields=['is_active'], name='core_teamop_is_acti_0d1838_idx'), models.Index(fields=['-created_at'], name='core_teamop_created_d5d022_idx')],
            },
        ),
    ]
