# Generated by Django 5.0.6 on 2025-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_historicaldatacollectionconfig_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='circuit_type',
            field=models.CharField(blank=True, help_text='Type of circuit (street circuit, permanent circuit, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='circuit',
            name='description',
            field=models.TextField(blank=True, help_text='General description of the circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='direction',
            field=models.CharField(blank=True, choices=[('clockwise', 'Clockwise'), ('anti-clockwise', 'Anti-clockwise')], help_text='Direction of the track', max_length=20),
        ),
        migrations.AddField(
            model_name='circuit',
            name='first_grand_prix',
            field=models.IntegerField(blank=True, help_text='Year of first Grand Prix', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='history',
            field=models.TextField(blank=True, help_text='Historical information and interesting facts about the circuit'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='lap_record',
            field=models.DurationField(blank=True, help_text='Lap record time', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='lap_record_driver',
            field=models.CharField(blank=True, help_text='Driver who holds the lap record', max_length=100),
        ),
        migrations.AddField(
            model_name='circuit',
            name='lap_record_year',
            field=models.IntegerField(blank=True, help_text='Year the lap record was set', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='layout_id',
            field=models.CharField(blank=True, help_text="Layout ID from f1-circuits-svg (e.g., 'monza-1')", max_length=50),
        ),
        migrations.AddField(
            model_name='circuit',
            name='number_of_corners',
            field=models.IntegerField(blank=True, help_text='Total number of corners', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='number_of_laps',
            field=models.IntegerField(blank=True, help_text='Number of laps in a standard race', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='race_distance_km',
            field=models.FloatField(blank=True, help_text='Total race distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='circuit',
            name='svg_url',
            field=models.URLField(blank=True, help_text='URL to SVG track layout from f1-circuits-svg repository'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='total_races_held',
            field=models.IntegerField(blank=True, help_text='Total number of races held at this circuit', null=True),
        ),
    ]
