# Generated by Django 5.0.6 on 2025-11-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_circuit_circuit_type_circuit_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDataCollectionConfig',
        ),
        migrations.DeleteModel(
            name='HistoricalDataGap',
        ),
    ]
